### ISSUE TITLE
Initial status of Order be 'Awaiting Acceptance' rather than 'Generating Label'

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#146] opened 2019-11-12 19:38 UTC
**Is your feature request related to a problem? Please describe.**
When I first made an order on Koeng102, the status of the order was 'Generating Label'. However, the first status is 'Awaiting Acceptance', since before a label is generated we first need to accept an order.

**Describe the solution you'd like**
For the initial status to be 'Awaiting Acceptance' rather than 'Generating Label' (or something along the lines of 'Awaiting Acceptance')

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment] 2019-11-12 19:43
This is a bit confusing, because the default is "Awaiting Countersign" and then only when you upload an MTA (or have one) it turns to Generating label. So, the first status would still be Awaiting Countersign, but then you are asking to insert another status before Generating label to be "'Awaiting Acceptance'? Is that not the same thing?

**Comment by vsoch** [comment] 2019-11-12 19:43
@hverdonk please weigh in

**Comment by vsoch** [comment] 2019-11-12 19:44
maybe you guys should sync up (in person?) on these first?

**Comment by hverdonk** [comment] 2019-11-12 23:04
We just synced up, and it looks like this is a bug. "Awaiting Countersign" is being bypassed when the user initially submits the MTA, rather than when the administrator submits the countersigned version. We do not need to insert an additional status.

**Comment by vsoch** [comment] 2019-11-12 23:14
Could you write out the steps in detail, and when each happens,eg:

 - creates an order (Card) --> "Cart"
 - submits the order with MTA "Cart" --> "Awaiting Countersign"

then...

**Comment by hverdonk** [comment] 2019-11-12 23:24
- creates an order (Card) --> "Cart"
- submits the order with MTA "Cart" --> "Awaiting Countersign"
- admin submits MTA "Awaiting Countersign" --> "Generating Label"
- create shipping label "Generating Label" --> "Waiting to ship"
- "Mark Shipped" button is pressed "Waiting to Ship" --> "Shipped"
- user marks package as received "Shipped" --> "Received"

At any time until "Mark Shipped" is pressed, the admin has the option to reject the request. Pressing the "Reject" button changes the current status to "Rejected"

**Comment by vsoch** [comment] 2019-11-12 23:26
Right now it goes from:

 - "Awaiting Countersign" -> "Generating Label"
 - admin generates label, then "Generating Label" -> "Waiting to Ship"
 - then when admin ships it, clicks "Mark as Shipped" and "Waiting to Ship" --> "Shipped"
 - then if a user views their orders, they can also click "Mark as Received" --> "Received"

Rejected is a valid status that can happen at any time, unless it's already been rejected. Looking at the above steps, I don't see any clear step where an approval has been done, although awaiting countersign might indicate the same thing (if they don't provide the countersign, it's not really approved).

**Comment by hverdonk** [comment] 2019-11-12 23:30
We don't need to add another status for "Awaiting Acceptance." There was some nomenclature confusion ("Awaiting Acceptance" --> "Awaiting Countersign") that has been resolved. The issue is that "Awaiting Countersign" gets changed to "Generating Label" when the *user* uploads an MTA, rather than an admin.

**Comment by vsoch** [comment] 2019-11-12 23:31
okay cool - and just to clarify - you are saying that when the user uploads an mta (and the admin hasn't yet) it is erroneously jumping to "Generating label" instead of awaiting countersign?

**Comment by hverdonk** [comment] 2019-11-12 23:31
Correct

**Comment by vsoch** [comment] 2019-11-12 23:31
ok perfecto! Will work on this tomorrow too.

**Comment by hverdonk** [comment] 2019-11-12 23:31
Awesome, thank you!

**Comment by vsoch** [comment] 2019-11-13 13:19
This is now fixed, I reported the issue in #143

**Closed by vsoch** 2019-11-13 13:19 UTC
